### PR TITLE
Make keyboard shortcut configurable

### PR DESCRIPTION
**Pull request by lleaff**
Adds config.json option for keyboard shortcut

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Thank you for taking the time to do the work yourself

**Comment by Arthur-Milchior** [comment]
This is updated.

FYI; I usually add a pattern for the shortcut, to ensure that it's a correct short-cut string.

**Comment by lleaff** [comment]
Oh I see, so just this:
```
"pattern": "^((([Cc][Tt][Rr][Ll]|[Aa][Ll][Tt]|[Ss][Hh][Ii][Ff][Tt])\\+){0,3}[a-zA-Z0-9])?$",
```
in `config.schema.json` is enough ?

**Comment by Arthur-Milchior** [comment]
I mean, that's far from perfect. It would accept "Ctrl+ctrl+c". But I guess it's enough to detect most mistakes made by users

What's horrible in json schema is that there is no way to add an option "ignore case"

**Pull request merged**
